name: docker_action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

inputs:
  run-command: # id of input
    description: "Command to run"
    required: true

runs:
  using: "Docker"
  image: "../../.ci/Dockerfile"
  args:
    - "../../${{inputs.run-command}}"
