name: build_debug

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: ./.github/actions/cpp
        with:
          run-command: ".ci/build_debug.sh"

